# -*- coding: utf-8 -*-
"""Lista 6 - tuplas e dicionários.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11yirhktmev5V6PGJMMY1TsXEmdUHiOeC

# Lista 6 - tuplas e dicionários

## Tuplas

1. Crie uma tupla com todos os números de 0 a 9. Explore a sintaxe: use e depois não use parênteses.
"""

tupla = 1,2,3,4
print(tupla)

"""2. Crie uma tupla com todos os pares entre 0 e 100 (inclusive).

"""



"""3. Crie uma função que recebe uma lista de números e devolve, nesta ordem, o mínimo, a média, o desvio padrão e o máximo.

"""



"""4. Crie uma função que recebe uma lista e retorna True se todos os seus elementos forem numéricos (int, float ou string contendo um int ou float) ou False do contrário. A função deve também retornar a lista tratada: transformar todas as entradas não numéricas em numéricas ou, no melhor caso, devolver a lista apenas.

"""



"""5. Faça uma função que recebe valores a, b e c, resolve a equação quadrática ax^2+ bx + c = 0 e retorna:

a. o valor de Δ onde Δ=b^2- 4ac;

b. uma tupla com o valor do ponto de mínimo ou máximo, onde, x_m=-b/2a e y_m  = -Δ/4a;

c. uma lista contendo as raízes (a lista pode ser vazia, caso Δ<0;  pode conter apenas um elemento, caso Δ = 0; ou conter duas raízes, caso Δ> 0).

"""



"""## Dicionários

1. Crie um dicionário cujas chaves são os meses do ano e os valores são a duração (em dias) de cada mês.
"""



""" 2. Imprima as chaves seguidas dos seus valores para o dicionário criado no exercício 1. """



"""3. Crie um dicionário para as seguintes relações:

‘Banana’: 3.0

‘Cebola’: 4.0

‘Maçã’: 5.7

‘Abacaxi’: 8.0
"""



""" 4. Altere o valor da chave ‘Maçã’ no dicionário do exercício anterior para 8.6.

"""



"""5. Crie uma função que receba os valores do nome, idade e e-mail de uma pessoa e guarde-os em um dicionário com as chaves ‘nome’, ‘idade’ e ‘email’, respectivamente. Sua função deve retornar esse dicionário.

"""



""" 6. Como você armazenaria a seguinte tabela usando apenas dicionários? Tente imprimir o valor correspondente da linha Pedro x Coluna B.

"""



"""7. Faça uma função que receba uma lista e conte quantas vezes cada elemento apareceu nessa lista. Essa função deverá guardar os dados em um dicionário no qual as chaves são os elementos da lista e os valores são a contagem de quantas vezes esse elemento aparece.

"""



""" 8. Faça um programa que fique pedindo uma resposta do usuário, entre 1, 2 e 3. Se o usuário digitar 1, o programa deve cadastrar um novo usuário nos moldes do exercício 5 e guardar esse cadastro num dicionário cuja chave será o CPF da pessoa. Quando o usuário digitar 2, o programa deve imprimir os usuários cadastrados; e se o usuário digitar 3, o programa deve fechar.

9. Implemente um sistema de busca para o programa do exercício 7, isso é, se o usuário digitar 4, procure um determinado usuário pelo seu CPF.

"""



""" 10. Faça o análogo do exercício 6 para strings: conte quantas vezes cada caracter apareceu nessa string e retorne um dicionário com essa contagem.

"""

